spring:
  application:
    name: aidd-task-api
  jpa:
    open-in-view: false

server:
  port: ${SERVER_PORT:8080}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
